<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="kraken" name="org.jboss.seam.test.unit.web.MultipartRequestTest" tests="1" failures="0" timestamp="30 Dec 2010 22:44:12 GMT" time="0,036" errors="1">
  <testcase name="testMultipartRequest" time="0,036" classname="org.jboss.seam.test.unit.web.MultipartRequestTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at org.jboss.seam.test.unit.web.MultipartRequestTest$1$1.read(MultipartRequestTest.java:63)
	at org.jboss.seam.web.MultipartRequestImpl.parseRequest(MultipartRequestImpl.java:305)
	at org.jboss.seam.web.MultipartRequestImpl.getParameterNames(MultipartRequestImpl.java:530)
	at org.jboss.seam.web.MultipartFilter.doFilter(MultipartFilter.java:84)
	at org.jboss.seam.test.unit.web.MultipartRequestTest.testMultipartRequest(MultipartRequestTest.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:675)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:848)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1119)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:315)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:310)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:272)
	at org.testng.SuiteRunner.run(SuiteRunner.java:221)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:945)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:884)
	at org.testng.TestNG.run(TestNG.java:818)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:96)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:179)
]]>
    </error>
  </testcase>
</testsuite>
